m = int(input('digite um valor em metros:'))
km = (m/1000)
hm = (m/100)
dam = (m/10)
dm = (m*10)
cm = (m*100)
mm = (m*1000)
print('{} metros tem \n{} quilômetros \n{} hectômetros \n{} decâmetros \n{} decímetros \n{} centimetros \n{} milímetros'.format(m, km, hm, dam, dm, cm,mm))